### ISSUE TITLE
partial smart quotes 

### ISSUE THREAD

**Issue by davidfarmer** [sj-graves/algorithms-book#2]
The LaTeX  ``infinite'' becomes < q >infinite< /q > in MBX.

But in your LaTeX source you write things like  ``infinite",
which gives the appropriate appearance in the PDF, but which technically is wrong
because the right hand delimiter is ", not ''.

If those are fixed in the LaTeX source, then the automatic conversion will give
the correct q tags.  Otherwise, those can later be fixed by hand in the MBX.

**Comment by sj-graves** [comment]
I think I'll (for now) fix them manually in the xml. I wrote a python script to convert the mbx filenames all to xml and preserve the internal references, so that the SageMathCloud syntax highlighting picks up on the xml; you'll see those changes push out sooner or later. I haven't noticed anything int he way of conversion errors. There are a few non-standard LaTeX things which didn't make the transition (\scr{E}, for instance) but I can iron those out on a case-by-case basis as I edit the book.

**Comment by davidfarmer** [comment]
It might be better if you explained to SageMathCloud that
mbx files are xml.

**Comment by davidfarmer** [comment]
Some people put this at the top of each file:

<?xml version="1.0" encoding="UTF-8" ?>

but I forget if that was to tell their editor it is an XML
file, or for some other reason
